import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';
const text=await readFile('dist/server/index.js','utf8');const worker=(await import('data:text/javascript;base64,'+Buffer.from(text).toString('base64'))).default;
class Bucket {body=null;etag=null;revision=0; async get(){return this.body?{etag:this.etag,json:async()=>JSON.parse(this.body)}:null;}async put(key,body,options){if(options.onlyIf?.etagMatches&&options.onlyIf.etagMatches!==this.etag)return null;if(options.onlyIf?.etagDoesNotMatch==='*'&&this.body)return null;this.body=body;this.etag=String(++this.revision);return {etag:this.etag};}}
test('refactored UI provides every element used by the client and the pixel character assets',async()=>{
 const html=await(await worker.fetch(new Request('https://game.test/'),{})).text();
 const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));
 for(const [,id] of html.matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.has(id),'Missing UI element '+id);
 for(const name of ['hero','cat','slime','bat','ghost','boss','chest','spark','fire'])for(const frame of [0,1])assert.ok(ids.has('pixel-'+name+'-'+frame));
 assert.match(html,/冒険者ゆっぴ/);assert.ok(!html.includes('/* APP_JS */'));assert.ok(!html.includes('/* CHARACTERS_JS */'));
});
test('page embeds a parseable client and contains no unresolved assets',async()=>{const r=await worker.fetch(new Request('https://game.test/'),{});assert.equal(r.status,200);const html=await r.text();assert.match(html,/音の冒険/);assert.match(html,/data:image\/webp;base64,/);assert.ok(!html.includes('__FOREST_ASSET__'));const js=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(js);});
test('R2 game persists across independent requests, with guarded purchases',async()=>{const env={BUCKET:new Bucket()};const first=await(await worker.fetch(new Request('https://game.test/api/game'),env)).json();assert.equal(first.game.coins,60);const train=await worker.fetch(new Request('https://game.test/api/game',{method:'POST',headers:{Origin:'https://game.test','Content-Type':'application/json'},body:'{"type":"train"}'}),env);assert.equal(train.status,200);const second=await(await worker.fetch(new Request('https://game.test/api/game'),env)).json();assert.equal(second.game.level,2);assert.equal(second.game.coins,20);const bad=await worker.fetch(new Request('https://game.test/api/game',{method:'POST',headers:{Origin:'https://game.test','Content-Type':'application/json'},body:'{"type":"hire"}'}),env);assert.equal(bad.status,400);assert.equal(JSON.parse(env.BUCKET.body).coins,20);});
test('cross-origin writes and missing storage fail clearly',async()=>{assert.equal((await worker.fetch(new Request('https://game.test/api/game',{method:'POST',headers:{Origin:'https://other.test','Content-Type':'application/json'},body:'{"type":"train"}'}),{BUCKET:new Bucket()})).status,403);assert.equal((await worker.fetch(new Request('https://game.test/api/game'),{})).status,503);});
